server:
  port: 3344

spring:
  application:
    # microservice name in Eureka Server
    name:  cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sanstwy27/spring-cloud-config
          search-paths:
            - spring-cloud-config
      #### branch
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka