server:
  port: 3344

spring:
  application:
    # microservice name in Eureka Server
    name:  cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sanstwy27/spring-cloud-config
          search-paths:
            - spring-cloud-config
      #### branch
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

## refresh by rabbitmq
# refresh all
# curl -X POST "http://localhost:3344/actuator/bus-refresh"
# refresh specific client
# curl -X POST "http://localhost:3344/actuator/bus-refresh/config-client:3355"
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'