server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
      stream:
        binders:
          # binding rabbitmq
          defaultRabbit: # define binder
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
        bindings:
          input: # channel
            destination: studyExchange # Exchange name
            content-type: application/json
            binder: defaultRabbit # which binder
            # group: atsanstwy27A

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # default 30 second
    lease-expiration-duration-in-seconds: 5 # default 90 second
    instance-id: receive-8802.com  # instance name on mq list
    prefer-ip-address: true







