server:
  port: 7001

eureka:
  instance:
    # eureka instance name
    hostname: eureka7001.com
  client:
    # false: disable self registration
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # localhost
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # cluster
      defaultZone: http://eureka7002.com:7002/eureka/