server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

# feign expiration time (OpenFeign with ribbon)
ribbon:
  # Max Service Time
  ReadTimeout: 5000
  # Max Connection Time
  ConnectTimeout: 5000

logging:
  level:
    # feign interface log
    com.atsanstwy27.springcloud.service.PaymentFeignService: debug